# Generated by Django 5.1 on 2024-08-27 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_post_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
        migrations.RenameModel(
            old_name='Liked',
            new_name='Like',
        ),
    ]
